import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/public-api/sidebar';

const sidebars: SidebarsConfig = {
  "get-started": [{type: 'autogenerated', dirName: 'get-started'}],
  "public-api": apiSidebar,
};

export default sidebars;
