import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "API",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Authentication",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/create-magic-link",
              label: "Generate login magic link",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-auth-token",
              label: "Obtain authentication token",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Domains",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/get-domains-overview",
              label: "List domains with the domain details",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/create-domain",
              label: "Create new domain",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-domains",
              label: "List domains",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/create-domains-batch",
              label: "Create new domains in batch",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-domain-by-id",
              label: "Get domain by ID",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/update-domain",
              label: "Update an existing domain",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "public-api/patch-domain",
              label: "Partially update a domain",
              className: "api-method patch",
            },
            {
              type: "doc",
              id: "public-api/delete-domain",
              label: "Delete a domain",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "public-api/get-domains-domain-setup",
              label: "Get setup info",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/post-domains-domain-setup",
              label: "Verify domain",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/search-domains",
              label: "🚧 Search and filter domains with advanced filtering and ordering",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/list-domain-groups",
              label: "List domain groups",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/create-domain-group",
              label: "Create a new domain group",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-domain-group-by-id",
              label: "Get domain group details",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/update-domain-group",
              label: "Update an existing domain group",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "public-api/delete-domain-group",
              label: "Delete a domain group",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "public-api/add-domains-to-group",
              label: "🚧 Add domains to a domain group",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/delete-domain-1",
              label: "Remove a domain from a domain group",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Alerting",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/create-webhook",
              label: "Create a new webhook",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/find-all-webhooks",
              label: "Get webhook list for specific owner",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-webhook-by-object-id",
              label: "Get a specific webhook",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/update-webhook",
              label: "Update a webhook",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "public-api/delete-webhook",
              label: "Delete a webhook",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "public-api/regenerate-secret",
              label: "Regenerate webhook secret",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-webhook-deliveries",
              label: "Get the list of webhook deliveries",
              className: "api-method get",
            },
          ],
        },
        {
          type: "category",
          label: "DNS Lookup",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/dns-lookup-for-a",
              label: "DNS lookup for a record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-a",
              label: "DNS lookup batch for a record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-aaaa",
              label: "DNS lookup for aaaa record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-aaaa",
              label: "DNS lookup batch for aaaa record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-ns",
              label: "DNS lookup for ns record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-ns",
              label: "DNS lookup batch for ns record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-mx",
              label: "DNS lookup for mx record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-mx",
              label: "DNS lookup batch for mx record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-ptr",
              label: "DNS lookup for ptr record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-ptr",
              label: "DNS lookup batch for ptr record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-txt",
              label: "DNS lookup for txt record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-txt",
              label: "DNS lookup batch for txt record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-cname",
              label: "DNS lookup for cname record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-cname",
              label: "DNS lookup batch for cname record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-dmarc-records-raw",
              label: "Get raw DMARC records",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-dmarc",
              label: "DNS lookup for dmarc record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-dmarc-record-by-structure",
              label: "Get DMARC record by structure",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-dmarc-record-structure",
              label: "Get DMARC record structure",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-dmarc",
              label: "DNS lookup batch for dmarc record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-verification-status-batch",
              label: "getVerificationStatusBatch",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-dkim",
              label: "DNS lookup for dkim record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-dkim-records-by-selectors-with-domain",
              label: "Get DKIM records by selectors with domain",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-dkim",
              label: "DNS lookup batch for dkim record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-spf",
              label: "DNS lookup for spf record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-spf",
              label: "DNS lookup batch for spf record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-spf-record-lookup-result",
              label: "Get SPF record lookup result",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-for-bimi",
              label: "DNS lookup for bimi record",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/dns-lookup-batch-bimi",
              label: "DNS lookup batch for bimi record",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/validate-bimi-record",
              label: "Validate BIMI record",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Aggregate Reports",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/get-report-raw-data",
              label: "Get RUA reports raw data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-report-by-id",
              label: "Get aggregate report by ID",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-distinct-property",
              label: "Get distinct property values",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-aggregations",
              label: "Get DMARC aggregations data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-volume-data",
              label: "Get RUA email volume data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-reports-for-period",
              label: "Get volume data by report period",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-authentication-pass-rate",
              label: "Get authentication pass rates",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Failure Reports",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/get-failure-reports",
              label: "Get failure reports",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-failure-report-by-id",
              label: "Get failure report by ID",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/download-eml",
              label: "Download EML file for a failure report",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/download-attachment",
              label: "Download specific attachment from a failure report",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/download-all-attachments",
              label: "Download all attachments as a ZIP archive",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/get-failure-reports-aggregates",
              label: "Get aggregated statistics for failure reports",
              className: "api-method get",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Partner API",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Organizations",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/create-organization",
              label: "Create a new organization",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-organizations",
              label: "List organizations",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/patch-organization",
              label: "Partially update existing organization",
              className: "api-method patch",
            },
            {
              type: "doc",
              id: "public-api/get-organization-by-id",
              label: "Get organization details",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/delete-organization",
              label: "Delete an organization",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Billing - Subscriptions & Pricing",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/list-plans",
              label: "List plans",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/list-subscriptions",
              label: "List subscriptions for an organization",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/cancel-subscription",
              label: "Cancel a subscription",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/renew-subscription",
              label: "Renew the subscription",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/assign-subscription",
              label: "Assign a subscription (partner-admin flow)",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/update-subscription-price",
              label: "Upgrade/downgrade plan",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Users",
          link: {
            type: "doc",
            id: "public-api/easydmarc-api",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "public-api/invite",
              label: "Invite user",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/create-2",
              label: "Create user",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/get-user",
              label: "Get User",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "public-api/post-revoke-organization-access",
              label: "Revoke org access",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "public-api/patch-change-personal-info",
              label: "Update User Info",
              className: "api-method patch",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
